### PR TITLE
Update from microsoft vcpkg

### PR DESCRIPTION
**Pull request by timautry**
Update from microsoft vcpkg

@eao197 eao197 [restinio] update to v.0.6.5 (microsoft#10208) c953d07
@kevinlul kevinlul [sqlite3] Update to 3.31.1 (microsoft#10241) ae8a224
@c72578 c72578 [tool-meson] Update to 0.53.2 (microsoft#10234) 2121698
@PhoebeHui PhoebeHui [bullet3] Add usage (microsoft#10226) df31c41
@maxGimeno @lrineau maxGimeno and lrineau [cgal] Upgrade to 5.0.2 (microsoft#10222) … 003513d
@Meorawr Meorawr [eastl] Update to 3.16.05 (microsoft#10216) bbb6558
@Meorawr Meorawr [eabase] Update to 2.09.12 (microsoft#10215) 605957f
@hkaiser hkaiser [hpx] Update to V1.4.1 (microsoft#10214) … 8d4b4ba
@orudge orudge [proj4] Update to version 6.3.1 (microsoft#10211) bf338dc
@jgiannuzzi jgiannuzzi [sdl2-mixer] Enable native MIDI support on macOS (microsoft#10201) 0babb75
@igl42 igl42 [blaze] Update to 3.7 (microsoft#10182) 0d8fb64
@SvenPStarFinanz SvenPStarFinanz [xmlsec] Add cmake target exports (microsoft#10207) … 50e689d
@danielaparker danielaparker [jsoncons] Update to v0.146.0 (microsoft#10165) … 053ade6
@Toxe Toxe [libmysql] Fix for missing "ADD_COMPILE_FLAGS" command (microsoft#10162) … 64f7f25
@JackBoosY JackBoosY [celero] Fix some macros (microsoft#10159) … 31ce75e
@Toxe Toxe [hyperscan] Add missing dependency boost-crc (microsoft#10148) … f71aa30
@kevinlul kevinlul [libgit2] Update to 0.99.0 (microsoft#10140) … 12caf95
@fundies fundies [pugixml] Fix debug library name (microsoft#10134) … 9e7db0c
@Pospelove Pospelove [icu] Fix typo (microsoft#10128) 98513a5
@lazyhamster lazyhamster [gmime] Update to 3.2.6 (microsoft#10112) 01a864d
@cdcseacave cdcseacave [openmvs] update to v1.1 (microsoft#10110) … 57c7de7

### CODE REVIEW

**Comment by cdcseacave** [comment]
@timautry pls stop spamming with these messages

**Comment by timautry** [comment]
@cdcseacave @Toxe 
cc: @microsoft/vcpkg @JackBoosY 

I do not create them. The Pull Request process from microsoft/vcpkg to my fork of timautry/vcpkg logs them automatically to everyone "**_Watching_**".

I was told to change the option from "**_Watching_**" to either "**_Not Watching_**", "**_Releases only_**" or "**_Ignoring_**" microsoft/vcpkg one will receive any actions regarding vcpkg, forks, pull requests, updates, etc.?

image

**Comment by timautry** [comment]
@cdcseacave @Toxe 
cc: @JackBoosY 

Oh, I see what you mean now, in my pull request narrative documentation where it shows the username who made each commit, hmm... ....
I will delete the @ in front of the username so it will not send it too each person. 
Duh, 
 - **I apologize to everyone for causing you to receive something you did not want.**
 -  **_I did not realize it would send it to each person, my mistake._**

**Comment by Toxe** [comment]
Don't worry, it's not a big deal. Just unnecessary and I'm glad you could fix it. All good.

**Pull request merged**
